#####################################基础配置#####################################
# 检测算法使用FCOS，backbone使用Resnet50，数据集使用roadsign的配置文件模板，本配置文件默认使用单卡，单卡的batch_size=1
# 检测模型的名称
architecture: FCOS
# 根据硬件选择是否使用GPU
use_gpu: true
# ### max_iters为最大迭代次数，而一个iter会运行batch_size * device_num张图片。batch_size在下面 TrainReader.batch_size设置。
max_iters: 9600
# log平滑参数
log_smooth_window: 20
# 模型保存文件夹
save_dir: output
# 每隔多少迭代保存模型
snapshot_iter: 200
# ### mAP 评估方式，mAP评估方式可以选择COCO和VOC或WIDERFACE，其中VOC有11point和integral两种评估方法
metric: COCO
# ### pretrain_weights 可以是imagenet的预训练好的分类模型权重，也可以是在VOC或COCO数据集上的预训练的检测模型权重
# 模型配置文件和权重文件可参考[模型库](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/MODEL_ZOO.md)
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/fcos_r50_fpn_1x.pdparams
weights: output/fcos_r50_roadsign_coco_template/best_model
# ### 根据用户数据设置类别数，注意不包含背景类
num_classes: 30
# finetune时忽略的参数，按照正则化匹配，匹配上的参数会被忽略掉
finetune_exclude_pretrained_params: ['fcos_head_cls_']

# FCOS检测模型的结构
FCOS:
  backbone: ResNet
  fpn: FPN
  fcos_head: FCOSHead

# 检测模型的backbone
ResNet:
  # norm_type
  norm_type: affine_channel
  # depth
  depth: 50
  # feature_maps
  feature_maps: [3, 4, 5]
  # freeze_at
  freeze_at: 2

FPN:
  min_level: 3
  max_level: 7
  num_chan: 256
  use_c5: false
  spatial_scale: [0.03125, 0.0625, 0.125]
  has_extra_convs: true

FCOSHead:
  num_classes: 4
  fpn_stride: [8, 16, 32, 64, 128]
  num_convs: 4
  norm_type: "gn"
  fcos_loss: FCOSLoss
  norm_reg_targets: True
  centerness_on_reg: True
  use_dcn_in_tower: False
  nms: MultiClassNMS

MultiClassNMS:
  score_threshold: 0.025
  nms_top_k: 1000
  keep_top_k: 100
  nms_threshold: 0.6
  background_label: -1

FCOSLoss:
  loss_alpha: 0.25
  loss_gamma: 2.0
  iou_loss_type: "giou"
  reg_weights: 1.0


LearningRate:
  # ### 学习率设置 参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/FAQ.md#faq%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
  # base_lr 由于预训练模型使用的是在COCO上的预训练模型。若loss出现nan，请将学习率再设置小一些试试。
  base_lr: 0.0001
  # 学习率规划器
  # 具体实现参考[API](fluid.layers.piecewise_decay)
  schedulers:
  # 学习率衰减策略
  - !PiecewiseDecay
    gamma: 0.1
    # milestones
    milestones:
    # ### 参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/FAQ.md#faq%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
    # ### 8/12 11/12
    - 6400
    - 8800
  # 在训练开始时，调低学习率为base_lr * start_factor，然后逐步增长到base_lr，这个过程叫学习率热身，按照以下公式更新学习率
  # linear_step = end_lr - start_lr
  # lr = start_lr + linear_step * (global_step / warmup_steps)
  # 具体实现参考[API](fluid.layers.linear_lr_warmup)
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 100

OptimizerBuilder:
  # 默认使用SGD+Momentum进行训练
  # 具体实现参考[API](fluid.optimizer)
  optimizer:
    momentum: 0.9
    type: Momentum
  # 默认使用SGD+Momentum进行训练
  # 具体实现参考[API](fluid.optimizer)
  regularizer:
    factor: 0.0001
    type: L2

#####################################数据配置#####################################

# 模型训练集设置参考
# 训练、验证、测试使用的数据配置主要区别在数据路径、模型输入、数据增强参数设置
# 如果使用 faster_reader.yml，下面的参数设置优先级高，faster_reader.yml中的参数设置，对于用自定义数据建议将数据配置文件写到下面。
# _READER_: 'faster_reader.yml'


TrainReader:
  # 训练过程中模型的输入设置
  # 包括图片，图片长宽高等基本信息，图片id，标记的目标框，类别等信息
  # 不同算法，不同数据集 inputs_def 不同，有的算法需要限制输入图像尺寸，有的不需要###
  inputs_def:
    # FasterRCNN 不限制输入图像尺寸
    # 不同算法，不同数据集 fields 不同###
    # VOC数据格式需要读取的字段，注意与COCO不同。注意TrainReader、EvalReader、TestReader字段略有不同

    # FasterRCNN
    fields: ['image', 'im_info', 'fcos_target']

  # 训练数据集路径
  dataset:
    # 指定数据集格式
    !COCODataSet
    #dataset/xxx/
    #├── annotations
    #│   ├── train.json
    #│   ├── valid.json
    #├── images
    #│   ├── xxx1.png
    #│   ├── xxx2.png
    #│   ├── xxx3.png
    #│   |   ...

    # 数据集相对路径
    dataset_dir: dataset/coco
    # 图片文件夹相对路径
    image_dir: images
    # anno_path
    anno_path: annotations/train.json

    # 对于VOC、COCO等比赛数据集，可以不指定类别标签文件，use_default_label可以是true。
    # 对于用户自定义数据，如果是VOC格式数据，use_default_label必须要设置成false，且需要提供label_list.txt。如果是COCO格式数据，不需要设置这个参数。
    # use_default_label: false

    # 是否包含背景类，若with_background=true，num_classes需要+1
    # FCOS with_background=false
    with_background: false


  # 1个GPU的batch size，默认为1。需要注意：每个iter迭代会运行batch_size * device_num张图片
  batch_size: 1
  # 共享内存bufsize，若内存有限，请设置小一些。
  bufsize: 2
  # 选择是否打乱所有样本的顺序
  shuffle: true
  # drop_empty 建议设置为true
  drop_empty: true
  # drop_last 如果最后一个batch的图片数量为奇数，选择是否丢掉这个batch不进行训练。
  # 注意，在某些情况下，drop_last=false时训练过程中可能会出错，建议训练时都设置为true
  drop_last: true
  # mixup_epoch
  mixup_epoch: -1
  # 选择是否使用多进程，默认为false
  use_process: false
  # 若选用多进程，设置使用多进程/线程的数目，默认为4，建议与CPU核数一致
  # 开启多进程后，占用内存会成倍增加，根据内存设置###
  worker_num: 4


  # 数据预处理和数据增强部分，此部分设置要特别注意###
  # 不同算法对数据的预处理流程不同，建议使用对应算法默认的数据处理流程。
  # 比如，YOLO、FPN算法，要求输入图像尺寸必须是32的整数倍

  # 以下是对一个batch中的每单张图片做的数据增强
  sample_transforms:
    # 读取Image图像为numpy数组
    # 可以选择将图片从BGR转到RGB，可以选择对一个batch中的图片做mixup增强
    - !DecodeImage
      to_rgb: true
    # 以prob概率随机反转
    - !RandomFlipImage
      prob: 0.5
    # 归一化
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: true
      is_channel_first: false
    # ResizeImage
    - !ResizeImage
      target_size: 800
      max_size: 1333
      interp: 1
      use_cv2: true
    # channel_first
    - !Permute
      channel_first: true
      to_bgr: false

  # 对一个batch中的所有图片做的数据增强
  batch_transforms:
    - !PadBatch
      pad_to_stride: 128
      use_padded_im_info: false

    - !Gt2FCOSTarget
      object_sizes_boundary: [64, 128, 256, 512]
      center_sampling_radius: 1.5
      downsample_ratios: [8, 16, 32, 64, 128]
      norm_reg_targets: True


EvalReader:
  # 评估过程中模型的输入设置
  # 1个GPU的batch size，默认为1。需要注意：每个iter迭代会运行batch_size * device_num张图片
  batch_size: 1
  # 共享内存bufsize，共享内存中训练样本数量是： bufsize * batch_size * 2 张图
  bufsize: 1
  # shuffle=false
  shuffle: false
  # 一般的评估时，batch_size=1，drop_empty可设置成 false
  drop_empty: false
  # 一般的评估时，batch_size=1，drop_last可设置成 false
  drop_last: false
  # 选择是否使用多进程，默认为false
  use_process: false
  # 若选用多进程，设置使用多进程/线程的数目，默认为4，建议与CPU核数一致
  # 开启多进程后，占用内存会成倍增加，根据内存设置 ###
  worker_num: 1

  inputs_def:
    # VOC数据格式需要读取的字段，注意与COCO不同
    # 不同算法，不同数据集 fields 不同 ###
    # YOLO系列 VOC格式数据： ['image', 'gt_bbox', 'gt_class', 'gt_score', 'is_difficult']，且需要设置num_max_boxes
    # YOLO系列 COCO格式数据：['image', 'gt_bbox', 'gt_class', 'gt_score']，且需要设置num_max_boxes

    ### fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class']

    # FasterRCNN
    fields: ['image', 'im_info', 'im_id', 'im_shape']

  # 评估数据集路径
  dataset:
    # 指定数据集格式
    !COCODataSet
    #dataset/xxx/
    #├── annotations
    #│   ├── train.json
    #│   ├── valid.json
    #├── images
    #│   ├── xxx1.png
    #│   ├── xxx2.png
    #│   ├── xxx3.png
    #│   |   ...

    # 数据集相对路径
    dataset_dir: dataset/coco
    # 图片文件夹相对路径
    image_dir: images
    # anno_path
    anno_path: annotations/valid.json

    # 对于VOC、COCO等比赛数据集，可以不指定类别标签文件，use_default_label可以是true。
    # 对于用户自定义数据，如果是VOC格式数据，use_default_label必须要设置成false，且需要提供label_list.txt。如果是COCO格式数据，不需要设置这个参数。
    # use_default_label: false

    # 是否包含背景类，若with_background=true，num_classes需要+1
    # FCOS with_background=false
    with_background: false

  # 单张图的 transforms
  sample_transforms:
  # DecodeImage
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  # 图像归一化
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: true
    is_channel_first: false
  # ResizeImage
  - !ResizeImage
    target_size: 800
    max_size: 1333
    interp: 1
    use_cv2: true
  # Permute
  - !Permute
    to_bgr: false
    channel_first: true
  
  batch_transforms:
  - !PadBatch
    pad_to_stride: 128
    use_padded_im_info: true

TestReader:
  # 测试过程中模型的输入设置
  # 预测时 batch_size设置为1
  batch_size: 1
  # 一般的预测时，batch_size=1，drop_empty可设置成 false
  drop_empty: false
  # 一般的预测时，batch_size=1，drop_last可设置成 false
  drop_last: false


  inputs_def:
    # FasterRCNN不限制输入图像尺寸
    # 预测时需要读取字段
    # fields 字段
    fields: ['image', 'im_info', 'im_id', 'im_shape']

  dataset:
    # 预测数据
    !ImageFolder
    anno_path: annotations/valid.json

    # 对于VOC、COCO等比赛数据集，可以不指定类别标签文件，use_default_label可以是true。
    # 对于用户自定义数据，如果是VOC格式数据，use_default_label必须要设置成false，且需要提供label_list.txt。如果是COCO格式数据，不需要设置这个参数。
    # use_default_label: false

    # 是否包含背景类，若with_background=true，num_classes需要+1
    # FCOS with_background=false
    with_background: false


  # 单张图的 transforms
  sample_transforms:
    # DecodeImage
    - !DecodeImage
      to_rgb: true
      # with_mixup default=false
      with_mixup: false
    # NormalizeImage
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: true
      is_channel_first: false
    # ResizeImage
    - !ResizeImage
      target_size: 800
      max_size: 1333
      interp: 1
      use_cv2: true
    # Permute
    - !Permute
      to_bgr: false
      channel_first: true
  batch_transforms:
    - !PadBatch
      pad_to_stride: 128
      use_padded_im_info: true
